apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sftp.fullname" . }}-sftp-cm
  labels:
    {{- include "sftp.labels" . | nindent 4 }}
    app.georchestra.org: sftp
data:
  authorized_keys: |
    {{- .Values.sftp.authorized_keys | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sftp.fullname" . }}-sftp-hostkeys-cm
  labels:
    {{- include "sftp.labels" . | nindent 4 }}
    app.georchestra.org: sftp
data:
  {{- range $filename, $contents := .Values.sftp.host_keys }}
  {{ $filename }}: |-
    {{- $contents | trim | nindent 4 }}
  {{- end }}
